// Package cpp lowers an IR Module to C++17 source code. The generated
// code links against `runtime/cpp` (a header-only mirror of the Go
// runtime in C++), which means a single test suite can be built either
// as a Go binary (via backend/golang) or a C++ binary (via this
// package) from exactly the same IR.
//
// Every generated function takes a reference to an ntt::TestcaseExec
// as its second argument; setverdict / getverdict / log all funnel
// through it so a generated binary can collect verdicts, reasons and
// log lines just like the Go backend. The bottom of the file emits a
// run_suite() driver that enumerates every testcase in the module
// and returns a vector of name/verdict/reason triples.
//
// CLEAN-ROOM DECLARATION: nothing in this package was derived from
// reading Titan source code. The interfaces mirror Titan's surface
// where the standard fixes the shape (component / port / verdict
// names) and where existing Nokia 4G/5G test ports link against; all
// implementation details were designed from the TTCN-3 standard plus
// public documentation. This keeps ntt's BSD-3 license posture clean
// even when the C++ output ships alongside Titan-licensed runtime
// code.
package cpp

import (
	"fmt"
	"io"
	"strings"

	"github.com/nokia/ntt/ir"
)

// Generate writes a C++17 translation unit for m to w.
func Generate(w io.Writer, m *ir.Module) error {
	fmt.Fprintf(w, "// Code generated by ntt-cpp-backend. DO NOT EDIT.\n")
	fmt.Fprintf(w, "// Clean-room derivation, no Titan sources read. BSD-3.\n\n")
	fmt.Fprintf(w, "#include <cstdint>\n")
	fmt.Fprintf(w, "#include <sstream>\n")
	fmt.Fprintf(w, "#include <string>\n")
	fmt.Fprintf(w, "#include <utility>\n")
	fmt.Fprintf(w, "#include <vector>\n\n")
	fmt.Fprintf(w, "#include \"ntt/runtime.hpp\"\n\n")
	fmt.Fprintf(w, "namespace ntt_tests {\n\n")

	for _, fn := range m.Functions {
		if err := writeFunction(w, fn); err != nil {
			return err
		}
	}

	writeSuiteDriver(w, m)

	fmt.Fprintf(w, "} // namespace ntt_tests\n")
	return nil
}

func writeFunction(w io.Writer, fn *ir.Function) error {
	ret := "void"
	if fn.Return != ir.TypeVoid {
		ret = cppType(fn.Return)
	}
	fmt.Fprintf(w, "// %s is the lowered IR form of %s.\n", cppName(fn.Name), fn.Name)
	fmt.Fprintf(w, "%s %s(::ntt::Context& ctx, ::ntt::TestcaseExec& exec", ret, cppName(fn.Name))
	for _, p := range fn.Params {
		fmt.Fprintf(w, ", %s v%d", cppType(p.Type), p.ID)
	}
	fmt.Fprintf(w, ") {\n")
	fmt.Fprintf(w, "    (void)ctx;\n")
	fmt.Fprintf(w, "    (void)exec;\n")
	for _, p := range fn.Params {
		fmt.Fprintf(w, "    (void)v%d;\n", p.ID)
	}

	paramIDs := map[int]bool{}
	for _, p := range fn.Params {
		paramIDs[p.ID] = true
	}
	declareValues(w, fn, paramIDs)

	if len(fn.Blocks) > 0 {
		fmt.Fprintf(w, "    goto %s;\n", cppLabel(fn.Blocks[0].Label))
	}

	for _, blk := range fn.Blocks {
		fmt.Fprintf(w, "\n%s:\n", cppLabel(blk.Label))
		for _, in := range blk.Instrs {
			if err := writeInstr(w, fn, in); err != nil {
				return err
			}
		}
	}
	fmt.Fprintf(w, "}\n\n")
	return nil
}

func declareValues(w io.Writer, fn *ir.Function, skip map[int]bool) {
	seen := map[int]bool{}
	for _, blk := range fn.Blocks {
		for _, in := range blk.Instrs {
			if in.Dst == nil || seen[in.Dst.ID] || skip[in.Dst.ID] {
				continue
			}
			seen[in.Dst.ID] = true
			fmt.Fprintf(w, "    %s v%d{};\n", cppType(in.Dst.Type), in.Dst.ID)
			fmt.Fprintf(w, "    (void)v%d;\n", in.Dst.ID)
		}
	}
}

func writeInstr(w io.Writer, fn *ir.Function, in *ir.Instr) error {
	switch in.Op {
	case ir.OpConstInt:
		fmt.Fprintf(w, "    v%d = %d;\n", in.Dst.ID, in.Aux.(int64))
	case ir.OpConstBool:
		val := "false"
		if in.Aux.(bool) {
			val = "true"
		}
		fmt.Fprintf(w, "    v%d = %s;\n", in.Dst.ID, val)
	case ir.OpConstString:
		fmt.Fprintf(w, "    v%d = %s;\n", in.Dst.ID, cppStringLiteral(in.Aux.(string)))
	case ir.OpAdd:
		fmt.Fprintf(w, "    v%d = v%d + v%d;\n", in.Dst.ID, in.Operands[0].ID, in.Operands[1].ID)
	case ir.OpSub:
		fmt.Fprintf(w, "    v%d = v%d - v%d;\n", in.Dst.ID, in.Operands[0].ID, in.Operands[1].ID)
	case ir.OpMul:
		fmt.Fprintf(w, "    v%d = v%d * v%d;\n", in.Dst.ID, in.Operands[0].ID, in.Operands[1].ID)
	case ir.OpDiv:
		fmt.Fprintf(w, "    v%d = v%d / v%d;\n", in.Dst.ID, in.Operands[0].ID, in.Operands[1].ID)
	case ir.OpMod, ir.OpRem:
		fmt.Fprintf(w, "    v%d = v%d %% v%d;\n", in.Dst.ID, in.Operands[0].ID, in.Operands[1].ID)
	case ir.OpConcat:
		fmt.Fprintf(w, "    v%d = v%d + v%d;\n", in.Dst.ID, in.Operands[0].ID, in.Operands[1].ID)
	case ir.OpLengthOf:
		fmt.Fprintf(w, "    v%d = static_cast<int64_t>(v%d.size());\n", in.Dst.ID, in.Operands[0].ID)
	case ir.OpCopy:
		fmt.Fprintf(w, "    v%d = v%d;\n", in.Dst.ID, in.Operands[0].ID)
	case ir.OpNeg:
		fmt.Fprintf(w, "    v%d = -v%d;\n", in.Dst.ID, in.Operands[0].ID)
	case ir.OpEq:
		fmt.Fprintf(w, "    v%d = (v%d == v%d);\n", in.Dst.ID, in.Operands[0].ID, in.Operands[1].ID)
	case ir.OpNe:
		fmt.Fprintf(w, "    v%d = (v%d != v%d);\n", in.Dst.ID, in.Operands[0].ID, in.Operands[1].ID)
	case ir.OpLt:
		fmt.Fprintf(w, "    v%d = (v%d < v%d);\n", in.Dst.ID, in.Operands[0].ID, in.Operands[1].ID)
	case ir.OpLe:
		fmt.Fprintf(w, "    v%d = (v%d <= v%d);\n", in.Dst.ID, in.Operands[0].ID, in.Operands[1].ID)
	case ir.OpGt:
		fmt.Fprintf(w, "    v%d = (v%d > v%d);\n", in.Dst.ID, in.Operands[0].ID, in.Operands[1].ID)
	case ir.OpGe:
		fmt.Fprintf(w, "    v%d = (v%d >= v%d);\n", in.Dst.ID, in.Operands[0].ID, in.Operands[1].ID)
	case ir.OpAnd:
		fmt.Fprintf(w, "    v%d = (v%d && v%d);\n", in.Dst.ID, in.Operands[0].ID, in.Operands[1].ID)
	case ir.OpOr:
		fmt.Fprintf(w, "    v%d = (v%d || v%d);\n", in.Dst.ID, in.Operands[0].ID, in.Operands[1].ID)
	case ir.OpNot:
		fmt.Fprintf(w, "    v%d = !v%d;\n", in.Dst.ID, in.Operands[0].ID)
	case ir.OpReturn:
		if fn.Return == ir.TypeVoid {
			fmt.Fprintf(w, "    return;\n")
		} else if len(in.Operands) > 0 {
			fmt.Fprintf(w, "    return v%d;\n", in.Operands[0].ID)
		} else {
			fmt.Fprintf(w, "    return %s{};\n", cppType(fn.Return))
		}
	case ir.OpBranch:
		fmt.Fprintf(w, "    goto %s;\n", cppLabel(in.Targets[0].Label))
	case ir.OpCondBranch:
		fmt.Fprintf(w, "    if (v%d) { goto %s; } else { goto %s; }\n",
			in.Operands[0].ID, cppLabel(in.Targets[0].Label), cppLabel(in.Targets[1].Label))
	case ir.OpSetVerdict:
		name := strings.ToUpper(in.Aux.(string)[:1]) + strings.ToLower(in.Aux.(string)[1:])
		if len(in.Operands) == 0 {
			fmt.Fprintf(w, "    exec.setVerdict(::ntt::Verdict::%s);\n", name)
		} else {
			fmt.Fprintf(w, "    {\n")
			fmt.Fprintf(w, "        std::ostringstream _oss;\n")
			for i, op := range in.Operands {
				if i > 0 {
					fmt.Fprintf(w, "        _oss << \" \";\n")
				}
				fmt.Fprintf(w, "        _oss << v%d;\n", op.ID)
			}
			fmt.Fprintf(w, "        exec.setVerdict(::ntt::Verdict::%s, _oss.str());\n", name)
			fmt.Fprintf(w, "    }\n")
		}
	case ir.OpGetVerdict:
		fmt.Fprintf(w, "    v%d = exec.getVerdict();\n", in.Dst.ID)
	case ir.OpLog:
		if len(in.Operands) == 0 {
			fmt.Fprintf(w, "    exec.log(\"\");\n")
		} else {
			fmt.Fprintf(w, "    {\n")
			fmt.Fprintf(w, "        std::ostringstream _oss;\n")
			for i, op := range in.Operands {
				if i > 0 {
					fmt.Fprintf(w, "        _oss << \" \";\n")
				}
				fmt.Fprintf(w, "        _oss << v%d;\n", op.ID)
			}
			fmt.Fprintf(w, "        exec.log(_oss.str());\n")
			fmt.Fprintf(w, "    }\n")
		}
	case ir.OpCall:
		name := in.Aux.(string)
		args := []string{"ctx", "exec"}
		for _, op := range in.Operands {
			args = append(args, fmt.Sprintf("v%d", op.ID))
		}
		if in.Dst != nil {
			fmt.Fprintf(w, "    v%d = %s(%s);\n", in.Dst.ID, cppName(name), strings.Join(args, ", "))
		} else {
			fmt.Fprintf(w, "    %s(%s);\n", cppName(name), strings.Join(args, ", "))
		}
	default:
		fmt.Fprintf(w, "    // TODO: %s\n", in.Op)
	}
	return nil
}

// writeSuiteDriver emits the C++ equivalent of the Go backend's
// RunSuite. It enumerates every testcase in declaration order,
// allocates a fresh TestcaseExec, invokes it, and pushes the result
// into the suite_result. The driver lives in the same namespace as
// the generated functions so a main() wrapping this is a one-line
// affair.
func writeSuiteDriver(w io.Writer, m *ir.Module) {
	fmt.Fprintf(w, "// SuiteName is the IR module name this package was generated from.\n")
	fmt.Fprintf(w, "static constexpr const char* kSuiteName = %s;\n\n", cppStringLiteral(m.Name))

	// SuiteCase carries everything the harness wants: name, verdict,
	// reason, and the log buffer. We define it next to the driver so
	// the generated binary doesn't need to know about ntt::SuiteResult
	// (which doesn't carry reasons by design - that's a stable runtime
	// type, not the generator's contract with main()).
	fmt.Fprintf(w, "struct SuiteCase {\n")
	fmt.Fprintf(w, "    std::string name;\n")
	fmt.Fprintf(w, "    ::ntt::Verdict verdict;\n")
	fmt.Fprintf(w, "    std::string reason;\n")
	fmt.Fprintf(w, "    std::vector<std::string> logs;\n")
	fmt.Fprintf(w, "};\n\n")

	fmt.Fprintf(w, "// run_suite executes every testcase in declaration order and\n")
	fmt.Fprintf(w, "// returns the per-case verdicts. Helper functions are skipped.\n")
	fmt.Fprintf(w, "inline std::vector<SuiteCase> run_suite() {\n")
	fmt.Fprintf(w, "    std::vector<SuiteCase> out;\n")
	fmt.Fprintf(w, "    ::ntt::Context ctx;\n")
	for _, fn := range m.Functions {
		if !fn.IsTestcase {
			continue
		}
		qname := m.Name + "." + fn.Name
		fmt.Fprintf(w, "    {\n")
		fmt.Fprintf(w, "        ::ntt::TestcaseExec exec(%s);\n", cppStringLiteral(qname))
		fmt.Fprintf(w, "        %s(ctx, exec);\n", cppName(fn.Name))
		fmt.Fprintf(w, "        SuiteCase c;\n")
		fmt.Fprintf(w, "        c.name = %s;\n", cppStringLiteral(qname))
		fmt.Fprintf(w, "        c.verdict = exec.getVerdict();\n")
		fmt.Fprintf(w, "        c.reason = exec.reason();\n")
		fmt.Fprintf(w, "        c.logs = exec.logs();\n")
		fmt.Fprintf(w, "        out.push_back(std::move(c));\n")
		fmt.Fprintf(w, "    }\n")
	}
	fmt.Fprintf(w, "    return out;\n")
	fmt.Fprintf(w, "}\n\n")
}

func cppType(t ir.Type) string {
	switch t {
	case ir.TypeInt:
		return "std::int64_t"
	case ir.TypeFloat:
		return "double"
	case ir.TypeBool:
		return "bool"
	case ir.TypeString:
		return "std::string"
	case ir.TypeBytes:
		return "std::vector<std::uint8_t>"
	case ir.TypeVerdict:
		return "::ntt::Verdict"
	case ir.TypeVoid:
		return "void"
	}
	return "::ntt::Value"
}

func cppName(s string) string {
	if s == "" {
		return "anon_func"
	}
	r := strings.NewReplacer(".", "_", "-", "_", " ", "_")
	return r.Replace(s)
}

func cppLabel(s string) string {
	r := strings.NewReplacer(".", "_", "-", "_", " ", "_")
	return "block_" + r.Replace(s)
}

func cppStringLiteral(s string) string {
	// Produce a raw string literal with a delimiter that cannot collide
	// with the content (a tiny hash of the bytes).
	delim := "ntt"
	for strings.Contains(s, ")"+delim+`"`) {
		delim += "_"
	}
	return fmt.Sprintf(`R"%s(%s)%s"`, delim, s, delim)
}
