// Code generated from ETSI ES 201 873-6 V4.12.1 Annex B (TCI-TL XML
// mapping, schemas *_v4_10_1.xsd) by gen/gen_schema.py; DO NOT EDIT.
//
// For every event element of the Log schema's Body, the child elements its
// Events type declares, in schema order, after the common Event content
// (the "am" element and the ts/src/line/name/id/type attributes). Element
// names are the schema's, not the abstract signature's (for example
// "transmission-failure", not "transmissionFailure"). See doc.go.

package tl

// Field is one child element of an event, as the schema declares it.
type Field struct {
	Name     string // element name
	Type     string // schema type, prefixed with its schema
	Optional bool   // minOccurs="0", or one alternative of a choice
	// Choice numbers the event's xsd:choice the element is an alternative
	// of, from 1; 0 outside any. Alt numbers the alternative, from 1.
	Choice, Alt int
}

// Schema lists each event's fields in the order the schema requires.
var Schema = map[string][]Field{
	"tliTcExecute": {
		{Name: "tcId", Type: "Types:TciTestCaseIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "dur", Type: "SimpleTypes:TriTimerDurationType", Optional: true},
	},
	"tliTcStart": {
		{Name: "tcId", Type: "Types:TciTestCaseIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "dur", Type: "SimpleTypes:TriTimerDurationType", Optional: true},
	},
	"tliTcStop": {
		{Name: "reason", Type: "SimpleTypes:TString", Optional: true},
	},
	"tliTcStarted": {
		{Name: "tcId", Type: "Types:TciTestCaseIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "dur", Type: "SimpleTypes:TriTimerDurationType", Optional: true},
	},
	"tliTcTerminated": {
		{Name: "tcId", Type: "Types:TciTestCaseIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "verdict", Type: "Values:VerdictValue", Optional: false},
		{Name: "reason", Type: "SimpleTypes:TString", Optional: true},
	},
	"tliCtrlStart":      {},
	"tliCtrlStop":       {},
	"tliCtrlTerminated": {},
	"tliMSend_m": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "to", Type: "Types:TriPortIdType", Optional: true},
		{Name: "msgValue", Type: "Values:Value", Optional: false},
		{Name: "addrValue", Type: "Values:Value", Optional: true},
		{Name: "encoder-failure", Type: "SimpleTypes:TciStatusType", Optional: true, Choice: 1, Alt: 1},
		{Name: "msg", Type: "Types:TriMessageType", Optional: true, Choice: 1, Alt: 2},
		{Name: "address", Type: "Types:TriAddressType", Optional: true, Choice: 1, Alt: 2},
		{Name: "transmission-failure", Type: "SimpleTypes:TriStatusType", Optional: true, Choice: 1, Alt: 2},
	},
	"tliMSend_c": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "to", Type: "Types:TriPortIdType", Optional: true},
		{Name: "msgValue", Type: "Values:Value", Optional: false},
		{Name: "transmission-failure", Type: "SimpleTypes:TriStatusType", Optional: true},
	},
	"tliMSend_m_BC": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "to", Type: "Types:TriPortIdType", Optional: true},
		{Name: "msgValue", Type: "Values:Value", Optional: false},
		{Name: "encoder-failure", Type: "SimpleTypes:TciStatusType", Optional: true, Choice: 1, Alt: 1},
		{Name: "msg", Type: "Types:TriMessageType", Optional: true, Choice: 1, Alt: 2},
		{Name: "transmission-failure", Type: "SimpleTypes:TriStatusType", Optional: true, Choice: 1, Alt: 2},
	},
	"tliMSend_c_BC": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "to", Type: "Types:TriPortIdListType", Optional: true},
		{Name: "msgValue", Type: "Values:Value", Optional: false},
		{Name: "transmission-failure", Type: "SimpleTypes:TriStatusType", Optional: true},
	},
	"tliMSend_m_MC": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "to", Type: "Types:TriPortIdType", Optional: true},
		{Name: "msgValue", Type: "Values:Value", Optional: false},
		{Name: "addrValues", Type: "Types:TciValueListType", Optional: true},
		{Name: "encoder-failure", Type: "SimpleTypes:TciStatusType", Optional: true, Choice: 1, Alt: 1},
		{Name: "msg", Type: "Types:TriMessageType", Optional: true, Choice: 1, Alt: 2},
		{Name: "addresses", Type: "Types:TriAddressListType", Optional: true, Choice: 1, Alt: 2},
		{Name: "transmission-failure", Type: "SimpleTypes:TriStatusType", Optional: true, Choice: 1, Alt: 2},
	},
	"tliMSend_c_MC": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "to", Type: "Types:TriPortIdListType", Optional: true},
		{Name: "msgValue", Type: "Values:Value", Optional: false},
		{Name: "transmission-failure", Type: "SimpleTypes:TriStatusType", Optional: true},
	},
	"tliMDetected_m": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "from", Type: "Types:TriPortIdType", Optional: true},
		{Name: "msgValue", Type: "Types:TriMessageType", Optional: false},
		{Name: "address", Type: "Types:TriAddressType", Optional: true},
	},
	"tliMDetected_c": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "from", Type: "Types:TriPortIdType", Optional: true},
		{Name: "msgValue", Type: "Values:Value", Optional: false},
	},
	"tliMMismatch_m": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "msgValue", Type: "Values:Value", Optional: false},
		{Name: "msgTmpl", Type: "Templates:TciValueTemplate", Optional: false},
		{Name: "diffs", Type: "Templates:TciValueDifferenceList", Optional: false},
		{Name: "addrValue", Type: "Values:Value", Optional: true},
		{Name: "addressTmpl", Type: "Templates:TciValueTemplate", Optional: true},
	},
	"tliMMismatch_c": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "msgValue", Type: "Values:Value", Optional: false},
		{Name: "msgTmpl", Type: "Templates:TciValueTemplate", Optional: false},
		{Name: "diffs", Type: "Templates:TciValueDifferenceList", Optional: false},
		{Name: "from", Type: "Types:TriComponentIdType", Optional: true},
		{Name: "fromTmpl", Type: "Templates:TciNonValueTemplate", Optional: true},
	},
	"tliMReceive_m": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "msgValue", Type: "Values:Value", Optional: true},
		{Name: "msgTmpl", Type: "Templates:TciValueTemplate", Optional: true},
		{Name: "addrValue", Type: "Values:Value", Optional: true},
		{Name: "addressTmpl", Type: "Templates:TciValueTemplate", Optional: true},
	},
	"tliMReceive_c": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "msgValue", Type: "Values:Value", Optional: true},
		{Name: "msgTmpl", Type: "Templates:TciValueTemplate", Optional: true},
		{Name: "from", Type: "Types:TriComponentIdType", Optional: true},
		{Name: "fromTmpl", Type: "Templates:TciNonValueTemplate", Optional: true},
	},
	"tliPrCall_m": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "to", Type: "Types:TriPortIdType", Optional: true},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "addrValue", Type: "Values:Value", Optional: true},
		{Name: "encoder-failure", Type: "SimpleTypes:TciStatusType", Optional: true, Choice: 1, Alt: 1},
		{Name: "triPars", Type: "Types:TriParameterListType", Optional: true, Choice: 1, Alt: 2},
		{Name: "address", Type: "Types:TriAddressType", Optional: true, Choice: 1, Alt: 2},
		{Name: "transmission-failure", Type: "SimpleTypes:TriStatusType", Optional: true, Choice: 1, Alt: 2},
	},
	"tliPrCall_c": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "to", Type: "Types:TriPortIdType", Optional: true},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "transmission-failure", Type: "SimpleTypes:TriStatusType", Optional: true},
	},
	"tliPrCall_m_BC": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "to", Type: "Types:TriPortIdType", Optional: true},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "encoder-failure", Type: "SimpleTypes:TciStatusType", Optional: true, Choice: 1, Alt: 1},
		{Name: "triPars", Type: "Types:TriParameterListType", Optional: true, Choice: 1, Alt: 2},
		{Name: "transmission-failure", Type: "SimpleTypes:TriStatusType", Optional: true, Choice: 1, Alt: 2},
	},
	"tliPrCall_c_BC": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "to", Type: "Types:TriPortIdListType", Optional: true},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "transmission-failure", Type: "SimpleTypes:TriStatusType", Optional: true},
	},
	"tliPrCall_m_MC": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "to", Type: "Types:TriPortIdType", Optional: true},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "addrValues", Type: "Types:TciValueListType", Optional: true},
		{Name: "encoder-failure", Type: "SimpleTypes:TciStatusType", Optional: true, Choice: 1, Alt: 1},
		{Name: "triPars", Type: "Types:TriParameterListType", Optional: true, Choice: 1, Alt: 2},
		{Name: "addresses", Type: "Types:TriAddressListType", Optional: true, Choice: 1, Alt: 2},
		{Name: "transmission-failure", Type: "SimpleTypes:TriStatusType", Optional: true, Choice: 1, Alt: 2},
	},
	"tliPrCall_c_MC": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "to", Type: "Types:TriPortIdListType", Optional: true},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "transmission-failure", Type: "SimpleTypes:TriStatusType", Optional: true},
	},
	"tliPrGetCallDetected_m": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "from", Type: "Types:TriPortIdType", Optional: true},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "triPars", Type: "Types:TriParameterListType", Optional: true},
		{Name: "address", Type: "Types:TriAddressType", Optional: true},
	},
	"tliPrGetCallDetected_c": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "from", Type: "Types:TriPortIdType", Optional: true},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
	},
	"tliPrGetCallMismatch_m": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "parsTmpl", Type: "Templates:TciValueTemplate", Optional: true},
		{Name: "diffs", Type: "Templates:TciValueDifferenceList", Optional: false},
		{Name: "addrValue", Type: "Values:Value", Optional: true},
		{Name: "addressTmpl", Type: "Templates:TciValueTemplate", Optional: true},
	},
	"tliPrGetCallMismatch_c": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "parsTmpl", Type: "Templates:TciValueTemplate", Optional: true},
		{Name: "diffs", Type: "Templates:TciValueDifferenceList", Optional: false},
		{Name: "from", Type: "Types:TriComponentIdType", Optional: true},
		{Name: "fromTmpl", Type: "Templates:TciNonValueTemplate", Optional: true},
	},
	"tliPrGetCall_m": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "parsTmpl", Type: "Templates:TciValueTemplate", Optional: true},
		{Name: "addrValue", Type: "Values:Value", Optional: true},
		{Name: "addressTmpl", Type: "Templates:TciValueTemplate", Optional: true},
	},
	"tliPrGetCall_c": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "parsTmpl", Type: "Templates:TciValueTemplate", Optional: true},
		{Name: "from", Type: "Types:TriComponentIdType", Optional: true},
		{Name: "fromTmpl", Type: "Templates:TciNonValueTemplate", Optional: true},
	},
	"tliPrReply_m": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "to", Type: "Types:TriPortIdType", Optional: true},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "replValue", Type: "Values:Value", Optional: true},
		{Name: "addrValue", Type: "Values:Value", Optional: true},
		{Name: "encoder-failure", Type: "SimpleTypes:TciStatusType", Optional: true, Choice: 1, Alt: 1},
		{Name: "triPars", Type: "Types:TriParameterListType", Optional: true, Choice: 1, Alt: 2},
		{Name: "repl", Type: "Types:TriParameterType", Optional: true, Choice: 1, Alt: 2},
		{Name: "address", Type: "Types:TriAddressType", Optional: true, Choice: 1, Alt: 2},
		{Name: "transmission-failure", Type: "SimpleTypes:TriStatusType", Optional: true, Choice: 1, Alt: 2},
	},
	"tliPrReply_c": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "to", Type: "Types:TriPortIdType", Optional: true},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "replValue", Type: "Values:Value", Optional: true},
		{Name: "transmission-failure", Type: "SimpleTypes:TriStatusType", Optional: true},
	},
	"tliPrReply_m_BC": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "to", Type: "Types:TriPortIdType", Optional: true},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "replValue", Type: "Values:Value", Optional: true},
		{Name: "encoder-failure", Type: "SimpleTypes:TciStatusType", Optional: true, Choice: 1, Alt: 1},
		{Name: "triPars", Type: "Types:TriParameterListType", Optional: true, Choice: 1, Alt: 2},
		{Name: "repl", Type: "Types:TriParameterType", Optional: true, Choice: 1, Alt: 2},
		{Name: "transmission-failure", Type: "SimpleTypes:TriStatusType", Optional: true, Choice: 1, Alt: 2},
	},
	"tliPrReply_c_BC": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "to", Type: "Types:TriPortIdListType", Optional: true},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "replValue", Type: "Values:Value", Optional: true},
		{Name: "transmission-failure", Type: "SimpleTypes:TriStatusType", Optional: true},
	},
	"tliPrReply_m_MC": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "to", Type: "Types:TriPortIdType", Optional: true},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "replValue", Type: "Values:Value", Optional: true},
		{Name: "addrValues", Type: "Types:TciValueListType", Optional: true},
		{Name: "encoder-failure", Type: "SimpleTypes:TciStatusType", Optional: true, Choice: 1, Alt: 1},
		{Name: "triPars", Type: "Types:TriParameterListType", Optional: true, Choice: 1, Alt: 2},
		{Name: "repl", Type: "Types:TriParameterType", Optional: true, Choice: 1, Alt: 2},
		{Name: "addresses", Type: "Types:TriAddressListType", Optional: true, Choice: 1, Alt: 2},
		{Name: "transmission-failure", Type: "SimpleTypes:TriStatusType", Optional: true, Choice: 1, Alt: 2},
	},
	"tliPrReply_c_MC": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "to", Type: "Types:TriPortIdListType", Optional: true},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "replValue", Type: "Values:Value", Optional: true},
		{Name: "transmission-failure", Type: "SimpleTypes:TriStatusType", Optional: true},
	},
	"tliPrGetReplyDetected_m": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "from", Type: "Types:TriPortIdType", Optional: true},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "triPars", Type: "Types:TriParameterListType", Optional: true},
		{Name: "repl", Type: "Types:TriParameterType", Optional: true},
		{Name: "address", Type: "Types:TriAddressType", Optional: true},
	},
	"tliPrGetReplyDetected_c": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "from", Type: "Types:TriPortIdType", Optional: true},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "replValue", Type: "Values:Value", Optional: true},
	},
	"tliPrGetReplyMismatch_m": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "parsTmpl", Type: "Templates:TciValueTemplate", Optional: true},
		{Name: "replValue", Type: "Values:Value", Optional: true},
		{Name: "replTmpl", Type: "Templates:TciValueTemplate", Optional: true},
		{Name: "diffs", Type: "Templates:TciValueDifferenceList", Optional: false},
		{Name: "addrValue", Type: "Values:Value", Optional: true},
		{Name: "addressTmpl", Type: "Templates:TciValueTemplate", Optional: true},
	},
	"tliPrGetReplyMismatch_c": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "parsTmpl", Type: "Templates:TciValueTemplate", Optional: true},
		{Name: "replValue", Type: "Values:Value", Optional: true},
		{Name: "replTmpl", Type: "Templates:TciValueTemplate", Optional: true},
		{Name: "diffs", Type: "Templates:TciValueDifferenceList", Optional: false},
		{Name: "from", Type: "Types:TriComponentIdType", Optional: true},
		{Name: "fromTmpl", Type: "Templates:TciNonValueTemplate", Optional: true},
	},
	"tliPrGetReply_m": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "parsTmpl", Type: "Templates:TciValueTemplate", Optional: true},
		{Name: "replValue", Type: "Values:Value", Optional: true},
		{Name: "replTmpl", Type: "Templates:TciValueTemplate", Optional: true},
		{Name: "addrValue", Type: "Values:Value", Optional: true},
		{Name: "addressTmpl", Type: "Templates:TciValueTemplate", Optional: true},
	},
	"tliPrGetReply_c": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "parsTmpl", Type: "Templates:TciValueTemplate", Optional: true},
		{Name: "replValue", Type: "Values:Value", Optional: true},
		{Name: "replTmpl", Type: "Templates:TciValueTemplate", Optional: true},
		{Name: "from", Type: "Types:TriComponentIdType", Optional: true},
		{Name: "fromTmpl", Type: "Templates:TciNonValueTemplate", Optional: true},
	},
	"tliPrRaise_m": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "to", Type: "Types:TriPortIdType", Optional: true},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "excValue", Type: "Values:Value", Optional: true},
		{Name: "addrValue", Type: "Values:Value", Optional: true},
		{Name: "encoder-failure", Type: "SimpleTypes:TciStatusType", Optional: true, Choice: 1, Alt: 1},
		{Name: "exc", Type: "Types:TriExceptionType", Optional: true, Choice: 1, Alt: 2},
		{Name: "address", Type: "Types:TriAddressType", Optional: true, Choice: 1, Alt: 2},
		{Name: "transmission-failure", Type: "SimpleTypes:TriStatusType", Optional: true, Choice: 1, Alt: 2},
	},
	"tliPrRaise_c": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "to", Type: "Types:TriPortIdType", Optional: true},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "excValue", Type: "Values:Value", Optional: true},
		{Name: "transmission-failure", Type: "SimpleTypes:TriStatusType", Optional: true},
	},
	"tliPrRaise_m_BC": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "to", Type: "Types:TriPortIdType", Optional: true},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "excValue", Type: "Values:Value", Optional: true},
		{Name: "encoder-failure", Type: "SimpleTypes:TciStatusType", Optional: true, Choice: 1, Alt: 1},
		{Name: "exc", Type: "Types:TriExceptionType", Optional: true, Choice: 1, Alt: 2},
		{Name: "transmission-failure", Type: "SimpleTypes:TriStatusType", Optional: true, Choice: 1, Alt: 2},
	},
	"tliPrRaise_c_BC": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "to", Type: "Types:TriPortIdListType", Optional: true},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "excValue", Type: "Values:Value", Optional: true},
		{Name: "transmission-failure", Type: "SimpleTypes:TriStatusType", Optional: true},
	},
	"tliPrRaise_m_MC": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "to", Type: "Types:TriPortIdType", Optional: true},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "excValue", Type: "Values:Value", Optional: true},
		{Name: "addrValues", Type: "Types:TciValueListType", Optional: true},
		{Name: "encoder-failure", Type: "SimpleTypes:TciStatusType", Optional: true, Choice: 1, Alt: 1},
		{Name: "exc", Type: "Types:TriExceptionType", Optional: true, Choice: 1, Alt: 2},
		{Name: "addresses", Type: "Types:TriAddressListType", Optional: true, Choice: 1, Alt: 2},
		{Name: "transmission-failure", Type: "SimpleTypes:TriStatusType", Optional: true, Choice: 1, Alt: 2},
	},
	"tliPrRaise_c_MC": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "to", Type: "Types:TriPortIdListType", Optional: true},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "excValue", Type: "Values:Value", Optional: true},
		{Name: "transmission-failure", Type: "SimpleTypes:TriStatusType", Optional: true},
	},
	"tliPrCatchDetected_m": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "from", Type: "Types:TriPortIdType", Optional: true},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "exc", Type: "Types:TriExceptionType", Optional: true},
		{Name: "address", Type: "Types:TriAddressType", Optional: true},
	},
	"tliPrCatchDetected_c": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "from", Type: "Types:TriPortIdType", Optional: true},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "excValue", Type: "Values:Value", Optional: true},
	},
	"tliPrCatchMismatch_m": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "excValue", Type: "Values:Value", Optional: true},
		{Name: "excTmpl", Type: "Templates:TciValueTemplate", Optional: true},
		{Name: "diffs", Type: "Templates:TciValueDifferenceList", Optional: false},
		{Name: "addrValue", Type: "Values:Value", Optional: true},
		{Name: "addressTmpl", Type: "Templates:TciValueTemplate", Optional: true},
	},
	"tliPrCatchMismatch_c": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "excValue", Type: "Values:Value", Optional: true},
		{Name: "excTmpl", Type: "Templates:TciValueTemplate", Optional: true},
		{Name: "diffs", Type: "Templates:TciValueDifferenceList", Optional: false},
		{Name: "from", Type: "Types:TriComponentIdType", Optional: true},
		{Name: "fromTmpl", Type: "Templates:TciNonValueTemplate", Optional: true},
	},
	"tliPrCatch_m": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "excValue", Type: "Values:Value", Optional: true},
		{Name: "excTmpl", Type: "Templates:TciValueTemplate", Optional: true},
		{Name: "addrValue", Type: "Values:Value", Optional: true},
		{Name: "addressTmpl", Type: "Templates:TciValueTemplate", Optional: true},
	},
	"tliPrCatch_c": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "excValue", Type: "Values:Value", Optional: true},
		{Name: "excTmpl", Type: "Templates:TciValueTemplate", Optional: true},
		{Name: "from", Type: "Types:TriComponentIdType", Optional: true},
		{Name: "fromTmpl", Type: "Templates:TciNonValueTemplate", Optional: true},
	},
	"tliPrCatchTimeoutDetected": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
	},
	"tliPrCatchTimeout": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
	},
	"tliCCreate": {
		{Name: "comp", Type: "Types:TriComponentIdType", Optional: false},
		{Name: "name", Type: "SimpleTypes:TString", Optional: false},
		{Name: "hostId", Type: "Values:Value", Optional: true},
		{Name: "alive", Type: "SimpleTypes:TBoolean", Optional: false},
	},
	"tliCStart": {
		{Name: "comp", Type: "Types:TriComponentIdType", Optional: false},
		{Name: "name", Type: "Types:TciBehaviourIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
	},
	"tliCRunning": {
		{Name: "comp", Type: "Types:TriComponentIdType", Optional: false},
		{Name: "status", Type: "SimpleTypes:ComponentStatusType", Optional: false},
	},
	"tliCAlive": {
		{Name: "comp", Type: "Types:TriComponentIdType", Optional: false},
		{Name: "status", Type: "SimpleTypes:ComponentStatusType", Optional: false},
	},
	"tliCStop": {
		{Name: "comp", Type: "Types:TriComponentIdType", Optional: false},
	},
	"tliCKill": {
		{Name: "comp", Type: "Types:TriComponentIdType", Optional: false},
	},
	"tliCDoneMismatch": {
		{Name: "comp", Type: "Types:TriComponentIdType", Optional: false},
		{Name: "compTmpl", Type: "Templates:TciNonValueTemplate", Optional: false},
	},
	"tliCDone": {
		{Name: "compTmpl", Type: "Templates:TciNonValueTemplate", Optional: false},
	},
	"tliCKilledMismatch": {
		{Name: "comp", Type: "Types:TriComponentIdType", Optional: false},
		{Name: "compTmpl", Type: "Templates:TciNonValueTemplate", Optional: false},
	},
	"tliCKilled": {
		{Name: "compTmpl", Type: "Templates:TciNonValueTemplate", Optional: false},
	},
	"tliCTerminated": {
		{Name: "verdict", Type: "Values:VerdictValue", Optional: false},
		{Name: "reason", Type: "SimpleTypes:TString", Optional: true},
	},
	"tliPConnect": {
		{Name: "port1", Type: "Types:TriPortIdType", Optional: false},
		{Name: "port2", Type: "Types:TriPortIdType", Optional: false},
	},
	"tliPDisconnect": {
		{Name: "port1", Type: "Types:TriPortIdType", Optional: false},
		{Name: "port2", Type: "Types:TriPortIdType", Optional: false},
	},
	"tliPMap": {
		{Name: "port1", Type: "Types:TriPortIdType", Optional: false},
		{Name: "port2", Type: "Types:TriPortIdType", Optional: false},
	},
	"tliPMapParam": {
		{Name: "port1", Type: "Types:TriPortIdType", Optional: false},
		{Name: "port2", Type: "Types:TriPortIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: false},
		{Name: "encoder-failure", Type: "SimpleTypes:TciStatusType", Optional: true, Choice: 1, Alt: 1},
		{Name: "triPars", Type: "Types:TriParameterListType", Optional: true, Choice: 1, Alt: 2},
	},
	"tliPUnmap": {
		{Name: "port1", Type: "Types:TriPortIdType", Optional: false},
		{Name: "port2", Type: "Types:TriPortIdType", Optional: false},
	},
	"tliPUnmapParam": {
		{Name: "port1", Type: "Types:TriPortIdType", Optional: false},
		{Name: "port2", Type: "Types:TriPortIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: false},
		{Name: "encoder-failure", Type: "SimpleTypes:TciStatusType", Optional: true, Choice: 1, Alt: 1},
		{Name: "triPars", Type: "Types:TriParameterListType", Optional: true, Choice: 1, Alt: 2},
	},
	"tliPClear": {
		{Name: "port", Type: "Types:TriPortIdType", Optional: false},
		{Name: "stat", Type: "SimpleTypes:PortStatusType", Optional: true},
	},
	"tliPStart": {
		{Name: "port", Type: "Types:TriPortIdType", Optional: false},
		{Name: "stat", Type: "SimpleTypes:PortStatusType", Optional: true},
	},
	"tliPStop": {
		{Name: "port", Type: "Types:TriPortIdType", Optional: false},
		{Name: "stat", Type: "SimpleTypes:PortStatusType", Optional: true},
	},
	"tliPHalt": {
		{Name: "port", Type: "Types:TriPortIdType", Optional: false},
		{Name: "stat", Type: "SimpleTypes:PortStatusType", Optional: true},
	},
	"tliDecode": {
		{Name: "msg", Type: "Types:TriMessageType", Optional: false},
		{Name: "decoder-failure", Type: "SimpleTypes:TciStatusType", Optional: true, Choice: 1, Alt: 1},
		{Name: "val", Type: "Values:Value", Optional: true, Choice: 1, Alt: 2},
		{Name: "codec", Type: "SimpleTypes:TString", Optional: true},
	},
	"tliEncode": {
		{Name: "val", Type: "Values:Value", Optional: false},
		{Name: "msg", Type: "Types:TriMessageType", Optional: true, Choice: 1, Alt: 1},
		{Name: "encoder-failure", Type: "SimpleTypes:TciStatusType", Optional: true, Choice: 1, Alt: 2},
		{Name: "codec", Type: "SimpleTypes:TString", Optional: true},
	},
	"tliTTimeoutDetected": {
		{Name: "timer", Type: "Types:TriTimerIdType", Optional: false},
	},
	"tliTTimeoutMismatch": {
		{Name: "timer", Type: "Types:TriTimerIdType", Optional: false},
		{Name: "timerTmpl", Type: "Templates:TciNonValueTemplate", Optional: false},
	},
	"tliTTimeout": {
		{Name: "timer", Type: "Types:TriTimerIdType", Optional: false},
		{Name: "timerTmpl", Type: "Templates:TciNonValueTemplate", Optional: false},
	},
	"tliTStart": {
		{Name: "timer", Type: "Types:TriTimerIdType", Optional: false},
		{Name: "dur", Type: "SimpleTypes:TriTimerDurationType", Optional: false},
	},
	"tliTStop": {
		{Name: "timer", Type: "Types:TriTimerIdType", Optional: false},
		{Name: "dur", Type: "SimpleTypes:TriTimerDurationType", Optional: false},
	},
	"tliTRead": {
		{Name: "timer", Type: "Types:TriTimerIdType", Optional: false},
		{Name: "elapsed", Type: "SimpleTypes:TriTimerDurationType", Optional: false},
	},
	"tliTRunning": {
		{Name: "timer", Type: "Types:TriTimerIdType", Optional: false},
		{Name: "status", Type: "SimpleTypes:TimerStatusType", Optional: false},
	},
	"tliSEnter": {
		{Name: "name", Type: "Types:QualifiedName", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "kind", Type: "SimpleTypes:TString", Optional: false},
	},
	"tliSLeave": {
		{Name: "name", Type: "Types:QualifiedName", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "returnValue", Type: "Values:Value", Optional: true},
		{Name: "kind", Type: "SimpleTypes:TString", Optional: false},
	},
	"tliVar": {
		{Name: "name", Type: "Types:QualifiedName", Optional: false},
		{Name: "val", Type: "Values:Value", Optional: true},
	},
	"tliModulePar": {
		{Name: "name", Type: "Types:QualifiedName", Optional: false},
		{Name: "val", Type: "Values:Value", Optional: true},
	},
	"tliGetVerdict": {
		{Name: "verdict", Type: "Values:VerdictValue", Optional: false},
	},
	"tliSetVerdict": {
		{Name: "verdict", Type: "Values:VerdictValue", Optional: false},
		{Name: "reason", Type: "SimpleTypes:TString", Optional: true},
	},
	"tliLog": {
		{Name: "log", Type: "SimpleTypes:TString", Optional: false},
	},
	"tliAEnter":    {},
	"tliALeave":    {},
	"tliADefaults": {},
	"tliAActivate": {
		{Name: "name", Type: "Types:QualifiedName", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "ref", Type: "Values:Value", Optional: false},
	},
	"tliADeactivate": {
		{Name: "ref", Type: "Values:Value", Optional: false},
	},
	"tliANomatch": {},
	"tliARepeat":  {},
	"tliAWait":    {},
	"tliAction": {
		{Name: "action", Type: "SimpleTypes:TString", Optional: false},
	},
	"tliMatch": {
		{Name: "expr", Type: "Values:Value", Optional: false},
		{Name: "tmpl", Type: "Templates:TciValueTemplate", Optional: false},
	},
	"tliMatchMismatch": {
		{Name: "expr", Type: "Values:Value", Optional: false},
		{Name: "tmpl", Type: "Templates:TciValueTemplate", Optional: false},
		{Name: "diffs", Type: "Templates:TciValueDifferenceList", Optional: false},
	},
	"tliInfo": {
		{Name: "level", Type: "SimpleTypes:TInteger", Optional: false},
		{Name: "info", Type: "SimpleTypes:TString", Optional: false},
	},
	"tliMChecked_m": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "msgValue", Type: "Values:Value", Optional: true},
		{Name: "msgTmpl", Type: "Templates:TciValueTemplate", Optional: true},
		{Name: "addrValue", Type: "Values:Value", Optional: true},
		{Name: "addressTmpl", Type: "Templates:TciValueTemplate", Optional: true},
	},
	"tliMChecked_c": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "msgValue", Type: "Values:Value", Optional: true},
		{Name: "msgTmpl", Type: "Templates:TciValueTemplate", Optional: true},
		{Name: "from", Type: "Types:TriComponentIdType", Optional: true},
		{Name: "fromTmpl", Type: "Templates:TciNonValueTemplate", Optional: true},
	},
	"tliPrGetCallChecked_m": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "parsTmpl", Type: "Templates:TciValueTemplate", Optional: true},
		{Name: "addrValue", Type: "Values:Value", Optional: true},
		{Name: "addressTmpl", Type: "Templates:TciValueTemplate", Optional: true},
	},
	"tliPrGetCallChecked_c": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "parsTmpl", Type: "Templates:TciValueTemplate", Optional: true},
		{Name: "from", Type: "Types:TriComponentIdType", Optional: true},
		{Name: "fromTmpl", Type: "Templates:TciNonValueTemplate", Optional: true},
	},
	"tliPrGetReplyChecked_m": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "parsTmpl", Type: "Templates:TciValueTemplate", Optional: true},
		{Name: "replValue", Type: "Values:Value", Optional: true},
		{Name: "replTmpl", Type: "Templates:TciValueTemplate", Optional: true},
		{Name: "addrValue", Type: "Values:Value", Optional: true},
		{Name: "addressTmpl", Type: "Templates:TciValueTemplate", Optional: true},
	},
	"tliPrGetReplyChecked_c": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "parsTmpl", Type: "Templates:TciValueTemplate", Optional: true},
		{Name: "replValue", Type: "Values:Value", Optional: true},
		{Name: "replTmpl", Type: "Templates:TciValueTemplate", Optional: true},
		{Name: "from", Type: "Types:TriComponentIdType", Optional: true},
		{Name: "fromTmpl", Type: "Templates:TciNonValueTemplate", Optional: true},
	},
	"tliPrCatchChecked_m": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "excValue", Type: "Values:Value", Optional: true},
		{Name: "excTmpl", Type: "Templates:TciValueTemplate", Optional: true},
		{Name: "addrValue", Type: "Values:Value", Optional: true},
		{Name: "addressTmpl", Type: "Templates:TciValueTemplate", Optional: true},
	},
	"tliPrCatchChecked_c": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "signature", Type: "Types:TriSignatureIdType", Optional: false},
		{Name: "excValue", Type: "Values:Value", Optional: true},
		{Name: "excTmpl", Type: "Templates:TciValueTemplate", Optional: true},
		{Name: "from", Type: "Types:TriComponentIdType", Optional: true},
		{Name: "fromTmpl", Type: "Templates:TciNonValueTemplate", Optional: true},
	},
	"tliCheckedAny_m": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "addrValue", Type: "Values:Value", Optional: true},
		{Name: "addressTmpl", Type: "Templates:TciValueTemplate", Optional: true},
	},
	"tliCheckedAny_c": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "from", Type: "Types:TriComponentIdType", Optional: true},
		{Name: "fromTmpl", Type: "Templates:TciNonValueTemplate", Optional: true},
	},
	"tliCheckAnyMismatch_m": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "addrValue", Type: "Values:Value", Optional: true},
		{Name: "addressTmpl", Type: "Templates:TciValueTemplate", Optional: true},
	},
	"tliCheckAnyMismatch_c": {
		{Name: "at", Type: "Types:TriPortIdType", Optional: false},
		{Name: "from", Type: "Types:TriComponentIdType", Optional: true},
		{Name: "fromTmpl", Type: "Templates:TciNonValueTemplate", Optional: true},
	},
	"tliRnd": {
		{Name: "val", Type: "Values:FloatValue", Optional: false},
		{Name: "from", Type: "Values:FloatValue", Optional: false},
	},
	"tliEvaluate": {
		{Name: "name", Type: "Types:QualifiedName", Optional: false},
		{Name: "evalResult", Type: "Values:Value", Optional: true},
	},
	"tliCCall": {
		{Name: "comp", Type: "Types:TriComponentIdType", Optional: false},
		{Name: "name", Type: "Types:TciBehaviourIdType", Optional: false},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
	},
	"tliCCallTerminated": {
		{Name: "verdict", Type: "Values:VerdictValue", Optional: false},
		{Name: "reason", Type: "SimpleTypes:TString", Optional: true},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
		{Name: "returnValue", Type: "Values:Value", Optional: true},
	},
	"tliCtrlStartWithParameters": {
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
	},
	"tliCtrlTerminatedWithResult": {
		{Name: "result", Type: "Values:Value", Optional: true},
		{Name: "tciPars", Type: "Types:TciParameterListType", Optional: true},
	},
}
