run:
  tests: false
  issues-exit-code: 0
  allow-parallel-runners: true
  concurrency: 0
  timeout: 10m

output:
  sort-results: true

linters:
  enable:
    - gocritic
    - dupl
    - dupword
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - exportloopref
    - forcetypeassert
    - gocognit
    - goconst
    - godot
    - godox
    - mnd
    - goprintffuncname
    - gosec
    - ireturn
    - maintidx
    - makezero
    - misspell
    - nestif
    - prealloc
    - revive
    - stylecheck
    - tenv
    - unconvert
    - usestdlibvars
    - varnamelen
    - wastedassign
    - wrapcheck

linters-settings:
  tagliatelle:
    case:
      rules:
        json: snake
        yaml: snake

issues:
  exclude-dirs:
    - internal/env
    - internal/fs
    - internal/loc
    - internal/lsp/fakenet
    - internal/lsp/helper
    - internal/lsp/jsonrpc2
    - internal/lsp/protocol
    - internal/lsp/span
    - internal/lsp/telemetry
    - internal/lsp/xcontext
    - internal/memoize
    - internal/session/flock
    - ttcn3/v2/syntax/internal/gen
    - ttcn3/syntax/internal/gen
    - ttcn3/printer

  exclude-files:
    - ".*_gen.go$"

  exclude-use-default: true
  exclude-case-sensitive: true
  exclude-dirs-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 3
  new: false
  fix: false
