before:
  hooks:
    - go mod download

builds:
  - id: ntt
    binary: ntt
    dir: .
    goos:
      - linux
      - darwin
      - windows
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386
      - goos: windows
        goarch: arm64


nfpms:
  - file_name_template: '{{ .ProjectName }}.{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage:  https://github.com/nokia/ntt
    description: A versatile TTCN-3 toolkit
    maintainer: Matthias Simon <matthias.simon@nokia.com>
    license: BSD-3 Clause
    vendor: Nokia

    formats:
      - deb
      - rpm

    recommends:
      - git
      - gcc
      - gcc-c++
      - golang

    bindir: /usr/bin
    replacements:
      386: i386
      amd64: x86_64

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    replacements:
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  draft: true
