language: go
go_import_path: github.com/nokia/ntt

matrix:
  include:
  - go: "1.12.x"
    script:  go test -v ./...
  - go: "tip"
    script: go test -v -mod=vendor ./...

env:
  - GO111MODULE=on

install: true
