# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BinaryString.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BinaryString.proto',
  package='ntt',
  syntax='proto3',
  serialized_options=b'Z\035github.com/nokia/ntt/protobuf',
  serialized_pb=b'\n\x12\x42inaryString.proto\x12\x03ntt\"+\n\x0c\x42inaryString\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05nbits\x18\x02 \x01(\x05\x42\x1fZ\x1dgithub.com/nokia/ntt/protobufb\x06proto3'
)




_BINARYSTRING = _descriptor.Descriptor(
  name='BinaryString',
  full_name='ntt.BinaryString',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='ntt.BinaryString.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nbits', full_name='ntt.BinaryString.nbits', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=70,
)

DESCRIPTOR.message_types_by_name['BinaryString'] = _BINARYSTRING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BinaryString = _reflection.GeneratedProtocolMessageType('BinaryString', (_message.Message,), {
  'DESCRIPTOR' : _BINARYSTRING,
  '__module__' : 'BinaryString_pb2'
  # @@protoc_insertion_point(class_scope:ntt.BinaryString)
  })
_sym_db.RegisterMessage(BinaryString)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
