# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generator.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import module_pb2 as module__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='generator.proto',
  package='ntt',
  syntax='proto3',
  serialized_options=b'Z\035github.com/nokia/ntt/protobuf',
  serialized_pb=b'\n\x0fgenerator.proto\x12\x03ntt\x1a\x0cmodule.proto\"6\n\x07Version\x12\r\n\x05major\x18\x01 \x01(\x05\x12\r\n\x05minor\x18\x02 \x01(\x05\x12\r\n\x05patch\x18\x03 \x01(\x05\"O\n\x10GeneratorRequest\x12\x1d\n\x07version\x18\x01 \x01(\x0b\x32\x0c.ntt.Version\x12\x1c\n\x07modules\x18\x02 \x03(\x0b\x32\x0b.ntt.Module\"\x13\n\x11GeneratorResponseB\x1fZ\x1dgithub.com/nokia/ntt/protobufb\x06proto3'
  ,
  dependencies=[module__pb2.DESCRIPTOR,])




_VERSION = _descriptor.Descriptor(
  name='Version',
  full_name='ntt.Version',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='major', full_name='ntt.Version.major', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='minor', full_name='ntt.Version.minor', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='patch', full_name='ntt.Version.patch', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=92,
)


_GENERATORREQUEST = _descriptor.Descriptor(
  name='GeneratorRequest',
  full_name='ntt.GeneratorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='ntt.GeneratorRequest.version', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='modules', full_name='ntt.GeneratorRequest.modules', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=173,
)


_GENERATORRESPONSE = _descriptor.Descriptor(
  name='GeneratorResponse',
  full_name='ntt.GeneratorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=194,
)

_GENERATORREQUEST.fields_by_name['version'].message_type = _VERSION
_GENERATORREQUEST.fields_by_name['modules'].message_type = module__pb2._MODULE
DESCRIPTOR.message_types_by_name['Version'] = _VERSION
DESCRIPTOR.message_types_by_name['GeneratorRequest'] = _GENERATORREQUEST
DESCRIPTOR.message_types_by_name['GeneratorResponse'] = _GENERATORRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Version = _reflection.GeneratedProtocolMessageType('Version', (_message.Message,), {
  'DESCRIPTOR' : _VERSION,
  '__module__' : 'generator_pb2'
  # @@protoc_insertion_point(class_scope:ntt.Version)
  })
_sym_db.RegisterMessage(Version)

GeneratorRequest = _reflection.GeneratedProtocolMessageType('GeneratorRequest', (_message.Message,), {
  'DESCRIPTOR' : _GENERATORREQUEST,
  '__module__' : 'generator_pb2'
  # @@protoc_insertion_point(class_scope:ntt.GeneratorRequest)
  })
_sym_db.RegisterMessage(GeneratorRequest)

GeneratorResponse = _reflection.GeneratedProtocolMessageType('GeneratorResponse', (_message.Message,), {
  'DESCRIPTOR' : _GENERATORRESPONSE,
  '__module__' : 'generator_pb2'
  # @@protoc_insertion_point(class_scope:ntt.GeneratorResponse)
  })
_sym_db.RegisterMessage(GeneratorResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
