// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.11.2
// source: parameter.proto

package protobuf

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Parameter_Direction int32

const (
	Parameter_IN    Parameter_Direction = 0
	Parameter_OUT   Parameter_Direction = 1
	Parameter_INOUT Parameter_Direction = 2
)

// Enum value maps for Parameter_Direction.
var (
	Parameter_Direction_name = map[int32]string{
		0: "IN",
		1: "OUT",
		2: "INOUT",
	}
	Parameter_Direction_value = map[string]int32{
		"IN":    0,
		"OUT":   1,
		"INOUT": 2,
	}
)

func (x Parameter_Direction) Enum() *Parameter_Direction {
	p := new(Parameter_Direction)
	*p = x
	return p
}

func (x Parameter_Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Parameter_Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_parameter_proto_enumTypes[0].Descriptor()
}

func (Parameter_Direction) Type() protoreflect.EnumType {
	return &file_parameter_proto_enumTypes[0]
}

func (x Parameter_Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Parameter_Direction.Descriptor instead.
func (Parameter_Direction) EnumDescriptor() ([]byte, []int) {
	return file_parameter_proto_rawDescGZIP(), []int{0, 0}
}

type Parameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Direction Parameter_Direction `protobuf:"varint,1,opt,name=direction,proto3,enum=ntt.Parameter_Direction" json:"direction,omitempty"`
	Value     *Value              `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Parameter) Reset() {
	*x = Parameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parameter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameter) ProtoMessage() {}

func (x *Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_parameter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameter.ProtoReflect.Descriptor instead.
func (*Parameter) Descriptor() ([]byte, []int) {
	return file_parameter_proto_rawDescGZIP(), []int{0}
}

func (x *Parameter) GetDirection() Parameter_Direction {
	if x != nil {
		return x.Direction
	}
	return Parameter_IN
}

func (x *Parameter) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_parameter_proto protoreflect.FileDescriptor

var file_parameter_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x6e, 0x74, 0x74, 0x1a, 0x0b, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x8e, 0x01, 0x0a, 0x09, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65,
	0x72, 0x12, 0x36, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x6e, 0x74, 0x74, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x65, 0x74, 0x65, 0x72, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6e, 0x74, 0x74, 0x2e, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x27, 0x0a, 0x09, 0x44,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x4e, 0x10, 0x00,
	0x12, 0x07, 0x0a, 0x03, 0x4f, 0x55, 0x54, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x4e, 0x4f,
	0x55, 0x54, 0x10, 0x02, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6e, 0x6f, 0x6b, 0x69, 0x61, 0x2f, 0x6e, 0x74, 0x74, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_parameter_proto_rawDescOnce sync.Once
	file_parameter_proto_rawDescData = file_parameter_proto_rawDesc
)

func file_parameter_proto_rawDescGZIP() []byte {
	file_parameter_proto_rawDescOnce.Do(func() {
		file_parameter_proto_rawDescData = protoimpl.X.CompressGZIP(file_parameter_proto_rawDescData)
	})
	return file_parameter_proto_rawDescData
}

var file_parameter_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_parameter_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_parameter_proto_goTypes = []interface{}{
	(Parameter_Direction)(0), // 0: ntt.Parameter.Direction
	(*Parameter)(nil),        // 1: ntt.Parameter
	(*Value)(nil),            // 2: ntt.Value
}
var file_parameter_proto_depIdxs = []int32{
	0, // 0: ntt.Parameter.direction:type_name -> ntt.Parameter.Direction
	2, // 1: ntt.Parameter.value:type_name -> ntt.Value
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_parameter_proto_init() }
func file_parameter_proto_init() {
	if File_parameter_proto != nil {
		return
	}
	file_value_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_parameter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Parameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_parameter_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_parameter_proto_goTypes,
		DependencyIndexes: file_parameter_proto_depIdxs,
		EnumInfos:         file_parameter_proto_enumTypes,
		MessageInfos:      file_parameter_proto_msgTypes,
	}.Build()
	File_parameter_proto = out.File
	file_parameter_proto_rawDesc = nil
	file_parameter_proto_goTypes = nil
	file_parameter_proto_depIdxs = nil
}
