# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parameter.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import value_pb2 as value__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='parameter.proto',
  package='ntt',
  syntax='proto3',
  serialized_options=b'Z\035github.com/nokia/ntt/protobuf',
  serialized_pb=b'\n\x0fparameter.proto\x12\x03ntt\x1a\x0bvalue.proto\"|\n\tParameter\x12+\n\tdirection\x18\x01 \x01(\x0e\x32\x18.ntt.Parameter.Direction\x12\x19\n\x05value\x18\x02 \x01(\x0b\x32\n.ntt.Value\"\'\n\tDirection\x12\x06\n\x02IN\x10\x00\x12\x07\n\x03OUT\x10\x01\x12\t\n\x05INOUT\x10\x02\x42\x1fZ\x1dgithub.com/nokia/ntt/protobufb\x06proto3'
  ,
  dependencies=[value__pb2.DESCRIPTOR,])



_PARAMETER_DIRECTION = _descriptor.EnumDescriptor(
  name='Direction',
  full_name='ntt.Parameter.Direction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OUT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INOUT', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=122,
  serialized_end=161,
)
_sym_db.RegisterEnumDescriptor(_PARAMETER_DIRECTION)


_PARAMETER = _descriptor.Descriptor(
  name='Parameter',
  full_name='ntt.Parameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='direction', full_name='ntt.Parameter.direction', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ntt.Parameter.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PARAMETER_DIRECTION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=161,
)

_PARAMETER.fields_by_name['direction'].enum_type = _PARAMETER_DIRECTION
_PARAMETER.fields_by_name['value'].message_type = value__pb2._VALUE
_PARAMETER_DIRECTION.containing_type = _PARAMETER
DESCRIPTOR.message_types_by_name['Parameter'] = _PARAMETER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Parameter = _reflection.GeneratedProtocolMessageType('Parameter', (_message.Message,), {
  'DESCRIPTOR' : _PARAMETER,
  '__module__' : 'parameter_pb2'
  # @@protoc_insertion_point(class_scope:ntt.Parameter)
  })
_sym_db.RegisterMessage(Parameter)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
