# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: value.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='value.proto',
  package='ntt',
  syntax='proto3',
  serialized_options=b'Z\035github.com/nokia/ntt/protobuf',
  serialized_pb=b'\n\x0bvalue.proto\x12\x03ntt\"\xe6\x01\n\x05Value\x12\x14\n\nbyte_value\x18\x01 \x01(\x0cH\x00\x12\x14\n\nbool_value\x18\x02 \x01(\x08H\x00\x12%\n\rverdict_value\x18\x03 \x01(\x0e\x32\x0c.ntt.VerdictH\x00\x12\x16\n\x0cstring_value\x18\x04 \x01(\tH\x00\x12\x15\n\x0b\x66loat_value\x18\x05 \x01(\x01H\x00\x12\x13\n\tint_value\x18\x06 \x01(\x05H\x00\x12\x13\n\tbig_value\x18\x07 \x01(\tH\x00\x12)\n\x0f\x63omposite_value\x18\x08 \x01(\x0b\x32\x0e.ntt.CompositeH\x00\x42\x06\n\x04kind\"\'\n\tComposite\x12\x1a\n\x06values\x18\x01 \x03(\x0b\x32\n.ntt.Value*>\n\x07Verdict\x12\x08\n\x04NONE\x10\x00\x12\x08\n\x04PASS\x10\x01\x12\n\n\x06INCONC\x10\x02\x12\x08\n\x04\x46\x41IL\x10\x03\x12\t\n\x05\x45RROR\x10\x04\x42\x1fZ\x1dgithub.com/nokia/ntt/protobufb\x06proto3'
)

_VERDICT = _descriptor.EnumDescriptor(
  name='Verdict',
  full_name='ntt.Verdict',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PASS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INCONC', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAIL', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=294,
  serialized_end=356,
)
_sym_db.RegisterEnumDescriptor(_VERDICT)

Verdict = enum_type_wrapper.EnumTypeWrapper(_VERDICT)
NONE = 0
PASS = 1
INCONC = 2
FAIL = 3
ERROR = 4



_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='ntt.Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='byte_value', full_name='ntt.Value.byte_value', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bool_value', full_name='ntt.Value.bool_value', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='verdict_value', full_name='ntt.Value.verdict_value', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='string_value', full_name='ntt.Value.string_value', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='float_value', full_name='ntt.Value.float_value', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int_value', full_name='ntt.Value.int_value', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='big_value', full_name='ntt.Value.big_value', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='composite_value', full_name='ntt.Value.composite_value', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='kind', full_name='ntt.Value.kind',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=21,
  serialized_end=251,
)


_COMPOSITE = _descriptor.Descriptor(
  name='Composite',
  full_name='ntt.Composite',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='ntt.Composite.values', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=292,
)

_VALUE.fields_by_name['verdict_value'].enum_type = _VERDICT
_VALUE.fields_by_name['composite_value'].message_type = _COMPOSITE
_VALUE.oneofs_by_name['kind'].fields.append(
  _VALUE.fields_by_name['byte_value'])
_VALUE.fields_by_name['byte_value'].containing_oneof = _VALUE.oneofs_by_name['kind']
_VALUE.oneofs_by_name['kind'].fields.append(
  _VALUE.fields_by_name['bool_value'])
_VALUE.fields_by_name['bool_value'].containing_oneof = _VALUE.oneofs_by_name['kind']
_VALUE.oneofs_by_name['kind'].fields.append(
  _VALUE.fields_by_name['verdict_value'])
_VALUE.fields_by_name['verdict_value'].containing_oneof = _VALUE.oneofs_by_name['kind']
_VALUE.oneofs_by_name['kind'].fields.append(
  _VALUE.fields_by_name['string_value'])
_VALUE.fields_by_name['string_value'].containing_oneof = _VALUE.oneofs_by_name['kind']
_VALUE.oneofs_by_name['kind'].fields.append(
  _VALUE.fields_by_name['float_value'])
_VALUE.fields_by_name['float_value'].containing_oneof = _VALUE.oneofs_by_name['kind']
_VALUE.oneofs_by_name['kind'].fields.append(
  _VALUE.fields_by_name['int_value'])
_VALUE.fields_by_name['int_value'].containing_oneof = _VALUE.oneofs_by_name['kind']
_VALUE.oneofs_by_name['kind'].fields.append(
  _VALUE.fields_by_name['big_value'])
_VALUE.fields_by_name['big_value'].containing_oneof = _VALUE.oneofs_by_name['kind']
_VALUE.oneofs_by_name['kind'].fields.append(
  _VALUE.fields_by_name['composite_value'])
_VALUE.fields_by_name['composite_value'].containing_oneof = _VALUE.oneofs_by_name['kind']
_COMPOSITE.fields_by_name['values'].message_type = _VALUE
DESCRIPTOR.message_types_by_name['Value'] = _VALUE
DESCRIPTOR.message_types_by_name['Composite'] = _COMPOSITE
DESCRIPTOR.enum_types_by_name['Verdict'] = _VERDICT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), {
  'DESCRIPTOR' : _VALUE,
  '__module__' : 'value_pb2'
  # @@protoc_insertion_point(class_scope:ntt.Value)
  })
_sym_db.RegisterMessage(Value)

Composite = _reflection.GeneratedProtocolMessageType('Composite', (_message.Message,), {
  'DESCRIPTOR' : _COMPOSITE,
  '__module__' : 'value_pb2'
  # @@protoc_insertion_point(class_scope:ntt.Composite)
  })
_sym_db.RegisterMessage(Composite)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
