#!/bin/bash -e

K3_PROJECT_ID=5154
K3_SOURCE_BRANCH="update-ntt-$CI_COMMIT_SHORT_SHA"
K3_TARGET_BRANCH="master"
HEADER="${CI_PROJECT_DIR}/header.txt"

TEMP="$(mktemp -d)"
trap "rm -rf -- $TEMP" EXIT

source <(curl https://gitlabe1.ext.net.nokia.com/k3/k3ci/-/raw/master/k3ci-configure-ssh)

function escapeJSON() {
    python -c 'import json; import sys; print(json.dumps(sys.stdin.read().strip()))' <<<"${@}"
}


cat >${HEADER} <<EOF
Private-Token: ${GITLAB_TOKEN}
Content-Type: application/json
EOF

set -x
git clone --depth=1 --no-tags --branch=master git@gitlabe1.ext.net.nokia.com:k3/k3.git $TEMP
cd $TEMP

if [ -n "${CI-}" ]; then
  git config --global user.email "${GIT_AUTHOR_EMAIL}"
  git config --global user.name  "${GIT_AUTHOR_NAME}"
fi

git checkout -b ${K3_SOURCE_BRANCH}
git submodule update --init lib/ntt
(cd lib/ntt; git fetch origin; git checkout $CI_COMMIT_SHA)
git add lib/ntt
git commit -am "$CI_COMMIT_MESSAGE"
git push --set-upstream origin ${K3_SOURCE_BRANCH}
curl >mr.json -X POST "${CI_API_V4_URL}/projects/$K3_PROJECT_ID/merge_requests" --header @$HEADER --data @- <<EOB
{
    "id": ${K3_PROJECT_ID},
    "assignee_id":"${GITLAB_USER_ID}",
    "source_branch": "${K3_SOURCE_BRANCH}",
    "target_branch": "${K3_TARGET_BRANCH}",
    "title": $(escapeJSON "${CI_COMMIT_TITLE}"),
    "description": $(escapeJSON "${CI_COMMIT_DESCRIPTION}"),
    "remove_source_branch": true,
    "squash_on_merge": true,
}
EOB
cat mr.json
MR_IID=$(grep -oP 'iid": *\K\d+' mr.json)
sleep 30
curl -X PUT "${CI_API_V4_URL}/projects/$K3_PROJECT_ID/merge_requests/${MR_IID}/merge" \
    --header @${HEADER} --data @- <<EOB
{
  "id": ${K3_PROJECT_ID},
  "merge_request_iid": ${MR_IID},
  "merge_when_pipeline_succeeds": true
}
EOB
