package golang_test

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/nokia/ntt/backend/golang"
)

// TestCodegen_CompilesUnderGoBuild proves the Go backend's output is a
// real, buildable Go package. We generate a fresh GOPATH module that
// imports the runtime/report package, write the codegen output, then
// invoke `go build` and assert success. This is what the M7 perf gate
// will eventually run before benchmarking.
func TestCodegen_CompilesUnderGoBuild(t *testing.T) {
	if _, err := exec.LookPath("go"); err != nil {
		t.Skip("no `go` binary on PATH")
	}
	dir := t.TempDir()

	// Set up a Go module that vendors-in just enough of the workspace
	// to compile the generated code via a replace directive.
	workspace, err := repoRoot()
	if err != nil {
		t.Skipf("cannot locate repository root: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte(`module sample
go 1.22
require github.com/nokia/ntt v0.0.0
replace github.com/nokia/ntt => `+workspace+`
`), 0o644); err != nil {
		t.Fatal(err)
	}

	var buf bytes.Buffer
	if err := golang.Generate(&buf, buildSampleModule()); err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "gen.go"), buf.Bytes(), 0o644); err != nil {
		t.Fatal(err)
	}

	cmd := exec.Command("go", "build", "./...")
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOFLAGS=-mod=mod")
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("go build failed: %v\n%s", err, out)
	}
}

// repoRoot returns the path of the closest enclosing directory with a
// go.mod file, walking up from the working directory.
func repoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", os.ErrNotExist
		}
		dir = parent
	}
}

// TestCodegen_OutputStartsWithGenerated_Header makes sure CI tooling
// can detect generated files via the standard header.
func TestCodegen_OutputStartsWithGenerated_Header(t *testing.T) {
	var buf bytes.Buffer
	if err := golang.Generate(&buf, buildSampleModule()); err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if !strings.HasPrefix(buf.String(), "// Code generated by ntt-go-backend.") {
		t.Errorf("missing generated header in output")
	}
}
