// Package golang lowers an IR Module to Go source code. The generated
// code links against the `runtime/*` packages (verdicts, ports, timers,
// alt scheduler) so the output of one IR module is a self-contained Go
// package the user can compile with `go build`.
//
// Code generation walks each Function block by block, mapping IR
// instructions to Go statements; SSA values become local variables. The
// resulting code reads naturally because the IR is already in the same
// shape (straight-line basic blocks, named conditional branches).
//
// Every generated function takes a *runtime.TestcaseExec as its first
// real argument; setverdict / getverdict / log all funnel through it
// so the harness can collect verdicts, reasons and log lines exactly
// like the tree-walking interpreter does. A `RunSuite` driver at the
// bottom of the file enumerates every testcase in the module and
// returns a slice of named verdicts the caller can render however
// they like (text, JSON, JUnit, ...).
//
// The package is called `golang` instead of `go` because `go` is a
// reserved keyword in Go modules.
package golang

import (
	"fmt"
	"io"
	"strings"

	"github.com/nokia/ntt/ir"
)

// Generate writes a Go source file for the IR module to w. The
// generated package name is `tests`; the caller can `gofmt` the
// output for stable layout.
func Generate(w io.Writer, m *ir.Module) error {
	fmt.Fprintf(w, "// Code generated by ntt-go-backend. DO NOT EDIT.\n")
	fmt.Fprintf(w, "package tests\n\n")
	fmt.Fprintf(w, "import (\n")
	fmt.Fprintf(w, "\t\"context\"\n")
	fmt.Fprintf(w, "\t\"fmt\"\n\n")
	fmt.Fprintf(w, "\t\"github.com/nokia/ntt/runtime\"\n")
	fmt.Fprintf(w, "\t\"github.com/nokia/ntt/runtime/report\"\n")
	fmt.Fprintf(w, ")\n\n")
	fmt.Fprintf(w, "var _ = context.Background\n")
	fmt.Fprintf(w, "var _ = fmt.Sprint\n\n")

	for _, fn := range m.Functions {
		if err := writeFunction(w, fn); err != nil {
			return err
		}
	}

	writeSuiteDriver(w, m)
	return nil
}

func writeFunction(w io.Writer, fn *ir.Function) error {
	fmt.Fprintf(w, "// %s is the lowered IR form of %s.\n", goName(fn.Name), fn.Name)
	fmt.Fprintf(w, "func %s(ctx context.Context, exec *runtime.TestcaseExec", goName(fn.Name))
	for _, p := range fn.Params {
		fmt.Fprintf(w, ", v%d %s", p.ID, goType(p.Type))
	}
	if fn.Return == ir.TypeVoid {
		fmt.Fprintf(w, ") error {\n")
	} else {
		fmt.Fprintf(w, ") (%s, error) {\n", goType(fn.Return))
	}
	fmt.Fprintf(w, "\t_ = ctx\n")
	fmt.Fprintf(w, "\t_ = exec\n")
	for _, p := range fn.Params {
		fmt.Fprintf(w, "\t_ = v%d\n", p.ID)
	}

	// Pre-declare every SSA value that's NOT a parameter so basic
	// blocks can be emitted in any order without forward-declaration
	// trouble. Parameters are already in scope from the signature.
	paramIDs := map[int]bool{}
	for _, p := range fn.Params {
		paramIDs[p.ID] = true
	}
	declareValues(w, fn, paramIDs)

	// Jump into the first block from the function preamble so the
	// `entry:` label is always referenced. This keeps the Go compiler
	// happy about declared-and-unused labels.
	if len(fn.Blocks) > 0 {
		fmt.Fprintf(w, "\tgoto %s\n", goLabel(fn.Blocks[0].Label))
	}

	for _, blk := range fn.Blocks {
		fmt.Fprintf(w, "\n%s:\n", goLabel(blk.Label))
		for _, in := range blk.Instrs {
			if err := writeInstr(w, fn, in); err != nil {
				return err
			}
		}
	}
	// Always close the function with a safe return so Go's
	// "missing return at end of function" check is satisfied. If
	// the IR already emitted a return in the final block this line
	// is unreachable and the compiler will elide it.
	if fn.Return == ir.TypeVoid {
		fmt.Fprintf(w, "\treturn nil\n")
	} else {
		var zero string
		switch fn.Return {
		case ir.TypeInt:
			zero = "0"
		case ir.TypeBool:
			zero = "false"
		case ir.TypeString:
			zero = `""`
		case ir.TypeVerdict:
			zero = "runtime.NoneVerdict"
		default:
			zero = "nil"
		}
		fmt.Fprintf(w, "\treturn %s, nil\n", zero)
	}
	fmt.Fprintf(w, "}\n\n")
	return nil
}

func declareValues(w io.Writer, fn *ir.Function, skip map[int]bool) {
	seen := map[int]bool{}
	for _, blk := range fn.Blocks {
		for _, in := range blk.Instrs {
			if in.Dst == nil || seen[in.Dst.ID] || skip[in.Dst.ID] {
				continue
			}
			seen[in.Dst.ID] = true
			fmt.Fprintf(w, "\tvar v%d %s\n", in.Dst.ID, goType(in.Dst.Type))
			fmt.Fprintf(w, "\t_ = v%d\n", in.Dst.ID)
		}
	}
}

func writeInstr(w io.Writer, fn *ir.Function, in *ir.Instr) error {
	switch in.Op {
	case ir.OpConstInt:
		fmt.Fprintf(w, "\tv%d = %d\n", in.Dst.ID, in.Aux.(int64))
	case ir.OpConstBool:
		fmt.Fprintf(w, "\tv%d = %t\n", in.Dst.ID, in.Aux.(bool))
	case ir.OpConstString:
		fmt.Fprintf(w, "\tv%d = %q\n", in.Dst.ID, in.Aux.(string))
	case ir.OpAdd:
		fmt.Fprintf(w, "\tv%d = v%d + v%d\n", in.Dst.ID, in.Operands[0].ID, in.Operands[1].ID)
	case ir.OpSub:
		fmt.Fprintf(w, "\tv%d = v%d - v%d\n", in.Dst.ID, in.Operands[0].ID, in.Operands[1].ID)
	case ir.OpMul:
		fmt.Fprintf(w, "\tv%d = v%d * v%d\n", in.Dst.ID, in.Operands[0].ID, in.Operands[1].ID)
	case ir.OpDiv:
		fmt.Fprintf(w, "\tv%d = v%d / v%d\n", in.Dst.ID, in.Operands[0].ID, in.Operands[1].ID)
	case ir.OpMod, ir.OpRem:
		fmt.Fprintf(w, "\tv%d = v%d %% v%d\n", in.Dst.ID, in.Operands[0].ID, in.Operands[1].ID)
	case ir.OpConcat:
		fmt.Fprintf(w, "\tv%d = v%d + v%d\n", in.Dst.ID, in.Operands[0].ID, in.Operands[1].ID)
	case ir.OpLengthOf:
		fmt.Fprintf(w, "\tv%d = int64(len(v%d))\n", in.Dst.ID, in.Operands[0].ID)
	case ir.OpCopy:
		fmt.Fprintf(w, "\tv%d = v%d\n", in.Dst.ID, in.Operands[0].ID)
	case ir.OpNeg:
		fmt.Fprintf(w, "\tv%d = -v%d\n", in.Dst.ID, in.Operands[0].ID)
	case ir.OpEq:
		fmt.Fprintf(w, "\tv%d = (v%d == v%d)\n", in.Dst.ID, in.Operands[0].ID, in.Operands[1].ID)
	case ir.OpNe:
		fmt.Fprintf(w, "\tv%d = (v%d != v%d)\n", in.Dst.ID, in.Operands[0].ID, in.Operands[1].ID)
	case ir.OpLt:
		fmt.Fprintf(w, "\tv%d = (v%d < v%d)\n", in.Dst.ID, in.Operands[0].ID, in.Operands[1].ID)
	case ir.OpLe:
		fmt.Fprintf(w, "\tv%d = (v%d <= v%d)\n", in.Dst.ID, in.Operands[0].ID, in.Operands[1].ID)
	case ir.OpGt:
		fmt.Fprintf(w, "\tv%d = (v%d > v%d)\n", in.Dst.ID, in.Operands[0].ID, in.Operands[1].ID)
	case ir.OpGe:
		fmt.Fprintf(w, "\tv%d = (v%d >= v%d)\n", in.Dst.ID, in.Operands[0].ID, in.Operands[1].ID)
	case ir.OpAnd:
		fmt.Fprintf(w, "\tv%d = v%d && v%d\n", in.Dst.ID, in.Operands[0].ID, in.Operands[1].ID)
	case ir.OpOr:
		fmt.Fprintf(w, "\tv%d = v%d || v%d\n", in.Dst.ID, in.Operands[0].ID, in.Operands[1].ID)
	case ir.OpNot:
		fmt.Fprintf(w, "\tv%d = !v%d\n", in.Dst.ID, in.Operands[0].ID)
	case ir.OpReturn:
		if len(in.Operands) > 0 {
			if fn.Return == ir.TypeVoid {
				fmt.Fprintf(w, "\treturn nil\n")
			} else {
				fmt.Fprintf(w, "\treturn v%d, nil\n", in.Operands[0].ID)
			}
		} else {
			if fn.Return == ir.TypeVoid {
				fmt.Fprintf(w, "\treturn nil\n")
			} else {
				var zero string
				switch fn.Return {
				case ir.TypeInt:
					zero = "0"
				case ir.TypeBool:
					zero = "false"
				case ir.TypeString:
					zero = `""`
				case ir.TypeVerdict:
					zero = "runtime.NoneVerdict"
				default:
					zero = "nil"
				}
				fmt.Fprintf(w, "\treturn %s, nil\n", zero)
			}
		}
	case ir.OpBranch:
		fmt.Fprintf(w, "\tgoto %s\n", goLabel(in.Targets[0].Label))
	case ir.OpCondBranch:
		fmt.Fprintf(w, "\tif v%d { goto %s } else { goto %s }\n",
			in.Operands[0].ID, goLabel(in.Targets[0].Label), goLabel(in.Targets[1].Label))
	case ir.OpSetVerdict:
		name := in.Aux.(string)
		// Reason arguments (if any) get stringified with %v and
		// joined with a single space, mirroring the interpreter's
		// evalSetverdict helper.
		if len(in.Operands) == 0 {
			fmt.Fprintf(w, "\texec.SetVerdict(runtime.%sVerdict, \"\")\n", capitalize(name))
		} else {
			parts := make([]string, 0, len(in.Operands))
			for _, op := range in.Operands {
				parts = append(parts, fmt.Sprintf("v%d", op.ID))
			}
			fmt.Fprintf(w, "\texec.SetVerdict(runtime.%sVerdict, fmt.Sprintf(\"%s\", %s))\n",
				capitalize(name),
				strings.Repeat("%v ", len(parts)),
				strings.Join(parts, ", "),
			)
		}
	case ir.OpGetVerdict:
		fmt.Fprintf(w, "\tv%d = exec.GetVerdict()\n", in.Dst.ID)
	case ir.OpLog:
		if len(in.Operands) == 0 {
			fmt.Fprintf(w, "\texec.Log(\"\")\n")
		} else {
			parts := make([]string, 0, len(in.Operands))
			for _, op := range in.Operands {
				parts = append(parts, fmt.Sprintf("v%d", op.ID))
			}
			fmt.Fprintf(w, "\texec.Log(fmt.Sprintf(\"%s\", %s))\n",
				strings.TrimRight(strings.Repeat("%v ", len(parts)), " "),
				strings.Join(parts, ", "),
			)
		}
	case ir.OpCall:
		name := in.Aux.(string)
		args := []string{"ctx", "exec"}
		for _, op := range in.Operands {
			args = append(args, fmt.Sprintf("v%d", op.ID))
		}
		if in.Dst != nil {
			fmt.Fprintf(w, "\tv%d, _ = %s(%s)\n", in.Dst.ID, goName(name), strings.Join(args, ", "))
		} else {
			fmt.Fprintf(w, "\t_ = %s(%s)\n", goName(name), strings.Join(args, ", "))
		}
	default:
		fmt.Fprintf(w, "\t// TODO: %s\n", in.Op)
	}
	return nil
}

// writeSuiteDriver emits a RunSuite function that wraps every
// testcase in a fresh TestcaseExec, invokes it, and returns a slice
// of name/verdict/reason triples. This is the integration surface
// `ntt run --target go` builds against; it also makes the generated
// package independently runnable from any Go program (e.g. an IDE).
func writeSuiteDriver(w io.Writer, m *ir.Module) {
	fmt.Fprintf(w, "// SuiteCase is one row in the RunSuite report.\n")
	fmt.Fprintf(w, "type SuiteCase struct {\n")
	fmt.Fprintf(w, "\tName    string\n")
	fmt.Fprintf(w, "\tVerdict report.Verdict\n")
	fmt.Fprintf(w, "\tReason  string\n")
	fmt.Fprintf(w, "\tLogs    []string\n")
	fmt.Fprintf(w, "}\n\n")

	fmt.Fprintf(w, "// SuiteName is the IR module name this package was generated from.\n")
	fmt.Fprintf(w, "const SuiteName = %q\n\n", m.Name)

	fmt.Fprintf(w, "// RunSuite executes every testcase in declaration order and\n")
	fmt.Fprintf(w, "// returns the per-case verdicts. Helper functions are not run.\n")
	fmt.Fprintf(w, "func RunSuite(ctx context.Context) []SuiteCase {\n")
	fmt.Fprintf(w, "\tvar out []SuiteCase\n")
	for _, fn := range m.Functions {
		if !fn.IsTestcase {
			continue
		}
		fmt.Fprintf(w, "\t{\n")
		fmt.Fprintf(w, "\t\texec := runtime.NewTestcaseExec(%q)\n", m.Name+"."+fn.Name)
		fmt.Fprintf(w, "\t\t_ = %s(ctx, exec)\n", goName(fn.Name))
		fmt.Fprintf(w, "\t\tout = append(out, SuiteCase{Name: %q, Verdict: mapVerdict(exec.GetVerdict()), Reason: exec.Reason(), Logs: exec.Logs()})\n", m.Name+"."+fn.Name)
		fmt.Fprintf(w, "\t}\n")
	}
	fmt.Fprintf(w, "\treturn out\n")
	fmt.Fprintf(w, "}\n\n")

	// Helper to translate runtime.Verdict (string enum) to the
	// fast int enum the report layer prefers.
	fmt.Fprintf(w, "func mapVerdict(v runtime.Verdict) report.Verdict {\n")
	fmt.Fprintf(w, "\tswitch v {\n")
	fmt.Fprintf(w, "\tcase runtime.PassVerdict:\n\t\treturn report.Pass\n")
	fmt.Fprintf(w, "\tcase runtime.InconcVerdict:\n\t\treturn report.Inconc\n")
	fmt.Fprintf(w, "\tcase runtime.FailVerdict:\n\t\treturn report.Fail\n")
	fmt.Fprintf(w, "\tcase runtime.ErrorVerdict:\n\t\treturn report.Error\n")
	fmt.Fprintf(w, "\t}\n")
	fmt.Fprintf(w, "\treturn report.None\n")
	fmt.Fprintf(w, "}\n")
}

func goType(t ir.Type) string {
	switch t {
	case ir.TypeInt:
		return "int64"
	case ir.TypeFloat:
		return "float64"
	case ir.TypeBool:
		return "bool"
	case ir.TypeString:
		return "string"
	case ir.TypeBytes:
		return "[]byte"
	case ir.TypeVerdict:
		return "runtime.Verdict"
	case ir.TypeVoid:
		return ""
	}
	return "interface{}"
}

func goName(s string) string {
	if s == "" {
		return "AnonFunc"
	}
	// Title-case so generated Go is exported. We split on the usual
	// TTCN-3 separator characters (`.`, `-`, `_`, space) and rejoin
	// without separators.
	parts := strings.FieldsFunc(s, func(r rune) bool {
		switch r {
		case '.', '-', '_', ' ':
			return true
		}
		return false
	})
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}

func goLabel(s string) string {
	r := strings.NewReplacer(".", "_", "-", "_", " ", "_")
	return "block_" + r.Replace(s)
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + strings.ToLower(s[1:])
}
